version: '3.7'
services:
  compactor-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - compactor-node
      - "--listen-addr"
      - "0.0.0.0:6660"
      - "--advertise-addr"
      - "compactor-0:6660"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1260"
      - "--metrics-level"
      - "1"
      - "--meta-address"
      - "http://meta-node-0:5690"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "6660"
      - "1260"
    ports: []
    depends_on:
      - meta-node-0
      - minio-0
    volumes:
      - "./rwave/risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: compactor-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/6660
      interval: 1s
      timeout: 5s
      retries: 5
    networks: 
      - pizzashop
  compute-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - compute-node
      - "--listen-addr"
      - "0.0.0.0:5688"
      - "--advertise-addr"
      - "compute-node-0:5688"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1222"
      - "--metrics-level"
      - "1"
      - "--meta-address"
      - "http://meta-node-0:5690"
      - "--connector-rpc-endpoint"
      - "connector-node:50051"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "5688"
      - "1222"
    ports: []
    depends_on:
      - meta-node-0
      - minio-0
    volumes:
      - "./rwave/risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: compute-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5688
      interval: 1s
      timeout: 5s
      retries: 5
    networks: 
      - pizzashop
  etcd-0:
    image: "quay.io/coreos/etcd:v3.5.7"
    command:
      - /usr/local/bin/etcd
      - "--listen-client-urls"
      - "http://0.0.0.0:2388"
      - "--advertise-client-urls"
      - "http://etcd-0:2388"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2389"
      - "--initial-advertise-peer-urls"
      - "http://etcd-0:2389"
      - "--listen-metrics-urls"
      - "http://0.0.0.0:2379"
      - "--name"
      - risedev-meta
      - "--max-txn-ops"
      - "999999"
      - "--max-request-bytes"
      - "10485760"
      - "--auto-compaction-mode"
      - periodic
      - "--auto-compaction-retention"
      - 1m
      - "--snapshot-count"
      - "10000"
    expose:
      - "2388"
    ports:
      - "2388:2388"
      - "2389:2389"
    depends_on: []
    volumes:
      - "etcd-0:/etcd-data"
    environment: {}
    container_name: etcd-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/2388
      interval: 1s
      timeout: 5s
      retries: 5
    networks: 
      - pizzashop
  frontend-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - frontend-node
      - "--listen-addr"
      - "0.0.0.0:4566"
      - "--meta-addr"
      - "http://meta-node-0:5690"
      - "--advertise-addr"
      - "frontend-node-0:4566"
      - "--config-path"
      - /risingwave.toml
      - "--prometheus-listener-addr"
      - "0.0.0.0:2222"
      - "--metrics-level"
      - "1"
    expose:
      - "4566"
    ports:
      - "4566:4566"
    depends_on:
      - meta-node-0
    volumes:
      - "./rwave/risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: frontend-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/4566
      interval: 1s
      timeout: 5s
      retries: 5
    networks: 
      - pizzashop
  meta-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - meta-node
      - "--listen-addr"
      - "0.0.0.0:5690"
      - "--advertise-addr"
      - "meta-node-0:5690"
      - "--dashboard-host"
      - "0.0.0.0:5691"
      - "--prometheus-host"
      - "0.0.0.0:1250"
      - "--backend"
      - etcd
      - "--etcd-endpoints"
      - "etcd-0:2388"
      - "--connector-rpc-endpoint"
      - "connector-node:50051"
      - "--state-store"
      - "hummock+minio://hummockadmin:hummockadmin@minio-0:9301/hummock001"
      - "--data-directory"
      - "hummock_001"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "5690"
      - "1250"
      - "5691"
    ports:
      - "5690:5690"
      - "5691:5691"
    depends_on:
      - "etcd-0"
    volumes:
      - "./rwave/risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: meta-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5690
      interval: 1s
      timeout: 5s
      retries: 5
    networks: 
      - pizzashop
  connector-node:
    image: ghcr.io/risingwavelabs/risingwave:latest
    entrypoint: "/risingwave/bin/connector-node/start-service.sh"
    ports:
      - 50051
      - 50052
    container_name: connector-node
    networks: 
      - pizzashop
  minio-0:
    image: "quay.io/minio/minio:latest"
    command:
      - server
      - "--address"
      - "0.0.0.0:9301"
      - "--console-address"
      - "0.0.0.0:9400"
      - /data
    expose:
      - "9301"
      - "9400"
    ports:
      - "9301:9301"
      - "9400:9400"
    depends_on: []
    volumes:
      - "minio-0:/data"
    entrypoint: "

      /bin/sh -c '

      set -e

      mkdir -p \"/data/hummock001\"

      /usr/bin/docker-entrypoint.sh \"$$0\" \"$$@\"

      '"
    environment:
      MINIO_CI_CD: "1"
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: "http://prometheus-0:9500"
      MINIO_ROOT_PASSWORD: hummockadmin
      MINIO_ROOT_USER: hummockadmin
    container_name: minio-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9301
      interval: 1s
      timeout: 5s
      retries: 5
    networks: 
      - pizzashop
  prometheus-0:
    image: "prom/prometheus:latest"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.listen-address=0.0.0.0:9500"
      - "--storage.tsdb.retention.time=30d"
    expose:
      - "9500"
    ports:
      - "9500:9500"
    depends_on: []
    volumes:
      - "prometheus-0:/prometheus"
      - "./rwave/prometheus.yaml:/etc/prometheus/prometheus.yml"
    environment: {}
    container_name: prometheus-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9500
      interval: 1s
      timeout: 5s
      retries: 5
    networks: 
      - pizzashop
volumes:
  etcd-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
networks:
  pizzashop:
    name: pizzashop